import { createClient } from '@libsql/client'
import { neon } from '@neondatabase/serverless'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const localDatabaseUrl = `file:${path.join(__dirname, '../budgeting.db')}`
const useNeon = Boolean(process.env.DATABASE_URL)
const client = useNeon ? null : createClient({
  url: process.env.TURSO_DATABASE_URL || localDatabaseUrl,
  ...(process.env.TURSO_AUTH_TOKEN ? { authToken: process.env.TURSO_AUTH_TOKEN } : {})
})
const sql = useNeon ? neon(process.env.DATABASE_URL) : null
const postgresSql = (statement) => {
  let parameterIndex = 0
  return statement
    .replace(/\?/g, () => `$${++parameterIndex}`)
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
}

const queryNeon = (statement, args = [], fullResults = false) => sql.query(postgresSql(statement), args, { fullResults })

export const db = {
  async exec(sql) {
    if (useNeon) {
      for (const statement of sql.split(';').map((entry) => entry.trim()).filter((entry) => entry && !/^PRAGMA\b/i.test(entry))) await queryNeon(statement)
      return
    }
    const statements = sql.split(';').map((statement) => statement.trim()).filter(Boolean)
    return client.batch(statements, 'write')
  },

  prepare(sql) {
    return {
      async get(...args) {
        if (useNeon) return (await queryNeon(sql, args))[0]
        const result = await client.execute({ sql, args })
        return result.rows[0]
      },
      async all(...args) {
        if (useNeon) return queryNeon(sql, args)
        const result = await client.execute({ sql, args })
        return result.rows
      },
      async run(...args) {
        if (useNeon) {
          const statement = /^INSERT\s/i.test(sql) && !/\bRETURNING\b/i.test(sql) ? `${sql} RETURNING id` : sql
          const result = await queryNeon(statement, args, true)
          return { changes: result.rowCount, lastInsertRowid: result.rows[0]?.id }
        }
        const result = await client.execute({ sql, args })
        return { changes: result.rowsAffected, lastInsertRowid: Number(result.lastInsertRowid) }
      }
    }
  }
}

export async function initializeDatabase() {
  await db.exec(`
    PRAGMA foreign_keys = ON;
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      email TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL DEFAULT '',
      password_hash TEXT NOT NULL,
      pin_hash TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS transactions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      date TEXT NOT NULL,
      income REAL NOT NULL DEFAULT 0,
      expenses REAL NOT NULL DEFAULT 0,
      savings REAL NOT NULL DEFAULT 0,
      note TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );
    CREATE TABLE IF NOT EXISTS consent_records (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER,
      policy_version TEXT NOT NULL,
      necessary INTEGER NOT NULL DEFAULT 1,
      analytics INTEGER NOT NULL DEFAULT 0,
      marketing INTEGER NOT NULL DEFAULT 0,
      preferences INTEGER NOT NULL DEFAULT 0,
      consented_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    );
  `)
  for (const statement of [
    "ALTER TABLE transactions ADD COLUMN note TEXT NOT NULL DEFAULT ''",
    'ALTER TABLE transactions ADD COLUMN savings REAL NOT NULL DEFAULT 0',
    "ALTER TABLE users ADD COLUMN name TEXT NOT NULL DEFAULT ''"
  ]) {
    try {
      await db.exec(statement)
    } catch (error) {
      if (!error.message.includes('duplicate column name') && error.code !== '42701') throw error
    }
  }
}
